### PR TITLE
Disable buttons instead of removing them

### PR DESCRIPTION
**Pull request by ghost**
This PR disables the pagination buttons instead of removing them upon timeout.

### CODE REVIEW

**Comment by devRael1** [comment]
Hey, 

Your update is interesting. I think it can be improved by making it so that you have the choice to remove or just disable the buttons. 

What do you think about it ?

**Comment by Macic-Dev** [comment]
Sure!

**Comment by ghost** [comment]
I had some time to work on this today, so I added a `disableButtons` option, which will disable the buttons when set to `true` and remove them when set to `false`.

**Comment by devRael1** [comment]
Don't worry, I've already done the update

**Pull request closed without merging**
